name: Exploring Workflow Dispatch Trigger

on:
  workflow_dispatch:
    inputs:
      run-job:
        description: 'Run Specific Job'
        required: false
        type: boolean
      custom-message:
        description: 'Enter a custom message'
        required: false
        type: string
        

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Exploring Workflow Dispatch Trigger"

  job2:
    runs-on: ubuntu-latest
    steps:
      - name: Printing Custom Message
        run: echo "${{ inputs.custom-message }}"
      - name: Printing run-job boolean value
        run: echo "${{ inputs.run-job }}"
        if: ${{ inputs.run-job == true }}
